# Generated by Django 2.0.2 on 2018-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groop',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='description goes here', max_length=500)),
                ('logo', models.ImageField(default='', upload_to='upload/')),
                ('website', models.URLField(default='google.com')),
                ('members', models.ManyToManyField(to='member.Member')),
            ],
        ),
    ]
