# Generated by Django 2.0.2 on 2018-02-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='groop',
        ),
        migrations.AddField(
            model_name='groop',
            name='logo',
            field=models.FileField(default='', upload_to='upload/'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
