# Generated by Django 2.0.2 on 2018-02-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groops', '0002_auto_20180203_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groop',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='groop',
            name='name',
        ),
    ]
