# Generated by Django 2.0.2 on 2018-02-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groops', '0003_auto_20180203_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='groop',
            name='description',
            field=models.CharField(default='testdefault', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groop',
            name='logo',
            field=models.FileField(default='', upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='groop',
            name='name',
            field=models.CharField(default='namedefault', max_length=100),
            preserve_default=False,
        ),
    ]
