# Generated by Django 2.0.2 on 2018-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groops', '0004_auto_20180203_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groop',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='groop',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
