# Generated by Django 2.0.2 on 2018-02-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groops', '0008_remove_groop_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groop',
            name='members',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='groops.Members'),
            preserve_default=False,
        ),
    ]
