# Generated by Django 2.0.2 on 2018-02-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groop',
            new_name='Event',
        ),
    ]
