# Generated by Django 2.0.2 on 2018-02-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(max_length=300)),
                ('day2', models.CharField(max_length=300)),
                ('day3', models.CharField(max_length=300)),
                ('day4', models.CharField(max_length=300)),
                ('day5', models.CharField(max_length=300)),
                ('day6', models.CharField(max_length=300)),
                ('day7', models.CharField(max_length=300)),
            ],
        ),
    ]
