# Generated by Django 2.0.2 on 2018-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
