# Generated by Django 2.0.2 on 2018-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bio', models.CharField(default='bio goes here', max_length=500)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('password', models.CharField(max_length=40)),
                ('profile_picture', models.ImageField(default='', upload_to='upload/')),
            ],
        ),
    ]
